version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: master
  ignore:
  - dependency-name: org.springframework.boot:spring-boot-dependencies
    versions:
    - 2.4.2
    - 2.4.3
    - 2.4.4
  - dependency-name: org.keycloak:keycloak-jetty94-adapter
    versions:
    - 12.0.2
    - 12.0.3
  - dependency-name: org.keycloak:keycloak-spring-security-adapter
    versions:
    - 12.0.2
    - 12.0.3
  - dependency-name: org.keycloak:keycloak-spring-boot-2-adapter
    versions:
    - 12.0.2
    - 12.0.3
  - dependency-name: org.keycloak:keycloak-authz-client
    versions:
    - 12.0.2
    - 12.0.3
  - dependency-name: org.apache.commons:commons-lang3
    versions:
    - "3.11"
  - dependency-name: com.fasterxml.jackson.core:jackson-databind
    versions:
    - 2.10.1
